server:
  jsp-servlet:
    init-parameters:
      development: true
  port: 9999
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vote
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: grk123
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:com/grk/mapper/*Mapper.xml
  type-aliases-package: com.grk.entity